

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/namkyu
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        fotmat_sql: true
        use_sql_comments: true
        #        show_sql: true


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace