

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/namkyu
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        fotmat_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace